pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test', 
                container("curl") {
                  script {
                    def status = pushDynatraceDeploymentEvent (
                      tagRule : { 
                                "meTypes" : "HOST",
                                "tags" : "Dev"  },
                      customProperties : [
                        [key: 'Jenkins Build Number', value: "${env.BUILD_ID}"],
                        [key: 'Git commit', value: "${env.GIT_COMMIT}"]
                      ]
                    )
                }
        }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
